services:
  - type: web
    name: pagina-sd-web
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: RABBITMQ_HOST
        value: rat.rmq2.cloudamqp.com
      - key: RABBITMQ_USER
        value: ssxppfqn
      - key: RABBITMQ_PASS
        value: fUxvCQey_0uAHrCbvTVTCvFicYLbm3eN
      - key: RPC_QUEUE
        value: rpc_queue

  - type: worker
    name: rpc-worker
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python rpc_server.py
    envVars:
      - key: RABBITMQ_HOST
        value: rat.rmq2.cloudamqp.com
      - key: RABBITMQ_USER
        value: ssxppfqn
      - key: RABBITMQ_PASS
        value: fUxvCQey_0uAHrCbvTVTCvFicYLbm3eN
      - key: RPC_QUEUE
        value: rpc_queue