services:
  - type: web
    name: food-dash
    runtime: python
    repo: https://github.com/mvelasquea/pagina_SD_web
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app